export const eventsObj = `[
  {
    "id": 1,
    "title": "Crystal Cup",
    "rating": true,
    "town": "Київ",
    "start": "2023-01-28",
    "end": "2023-01-28",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Анна Владикіна",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 2,
    "title": "Відкритий чемпіонат УАВТ (UDTA)",
    "rating": true,
    "town": "Київ",
    "start": "2023-02-11",
    "end": "2023-02-12",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Юрій та Яна Васютяк",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 3,
    "title": "Odesa Winter Championship",
    "rating": false,
    "town": "Одеса",
    "start": "2023-02-18",
    "end": "2023-02-18",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Євген Герасименко",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 4,
    "title": "ПроАрт",
    "rating": false,
    "town": "Київ",
    "start": "2023-02-18",
    "end": "2023-02-18",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Ярослав та Олена Скоренко",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 5,
    "title": "Crystal Dance Cup",
    "rating": false,
    "town": "Черкаси",
    "start": "2023-02-18",
    "end": "2023-02-18",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Андрій Мунтян",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 6,
    "title": "Carpatian Dance Cup",
    "rating": false,
    "town": "Івано-Франківськ",
    "start": "2023-02-18",
    "end": "2023-02-18",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Олег Гулій, Павло Яцик та Вадим Остапчук",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 7,
    "title": "Танцювальний марафон",
    "rating": false,
    "town": "Тернопіль",
    "start": "2023-02-25",
    "end": "2023-02-25",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Ігор та Ольга Полигач",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 8,
    "title": "Чарівність",
    "rating": false,
    "town": "Київ",
    "start": "2023-04-02",
    "end": "2023-04-02",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Світлана Макода, Олена Пахомова",
    "status": "Відкриті міські класифікаційні",
    "spartak": true,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt.",
    "address": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5076.819307494724!2d30.494291764116188!3d50.489333048678844!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cdf953e66b81%3A0xa97983168ec0777e!2z0L_RgC3Rgi4g0KHRgtC10L_QsNC90LAg0JHQsNC90LTQtdGA0YssIDIzLCDQmtC40LXQsiwgMDQ2NTU!5e0!3m2!1sru!2sua!4v1677584501191!5m2!1sru!2sua"
  },
  {
    "id": 9,
    "title": "Star Trek",
    "rating": false,
    "town": "Рівне",
    "start": "2023-03-04",
    "end": "2023-03-04",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Роман Гриценюк та Максим Малютчик",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 10,
    "title": "Kyiv Ball",
    "rating": true,
    "town": "Київ",
    "start": "2023-03-11",
    "end": "2023-03-12",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Максим Леонов та Дмитро Влох",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 11,
    "title": "Перлини Сезону",
    "rating": false,
    "town": "Київ",
    "start": "2023-03-18",
    "end": "2023-03-18",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Максим Пелих та Андрій Городецький",
    "status": "Відкриті міські класифікаційні",
    "spartak": true,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 12,
    "title": "Кубок Глорії",
    "rating": false,
    "town": "Івано-Франківськ",
    "start": "2023-03-18",
    "end": "2023-03-18",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Віталій Савчук",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 13,
    "title": "Dnipro Super Cup",
    "rating": false,
    "town": "Дніпро",
    "start": "2023-03-18",
    "end": "2023-03-19",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Сергій Дехтярьов",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 14,
    "title": "Парад Надій",
    "rating": true,
    "town": "Київ",
    "start": "2023-03-25",
    "end": "2023-03-25",
    "organization": "ВРСТ, СГОСТУ",
    "foreign": false,
    "organizator": "Валентина Федорчук та Альона Лемішко",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 15,
    "title": "Victory Smile Cup",
    "rating": false,
    "town": "Київ",
    "start": "2023-04-01",
    "end": "2023-04-01",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Олексій та Тетяна Балла",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 17,
    "title": "Rivne Open",
    "rating": false,
    "town": "Рівне",
    "start": "2023-04-08",
    "end": "2023-04-08",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Роман Гриценюк",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 18,
    "title": "Танцювальна сімʼя",
    "rating": false,
    "town": "Київ",
    "start": "2023-04-08",
    "end": "2023-04-08",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Ігор Огійчук",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 19,
    "title": "Танцювальний марафон",
    "rating": false,
    "town": "Київ",
    "start": "2023-04-09",
    "end": "2023-04-09",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Володимир Мачулка та Дмитро Белуха",
    "status": "Відкриті міські класифікаційні",
    "spartak": true,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 20,
    "title": "Ternopil Grande Cup",
    "rating": true,
    "town": "Тернопіль",
    "start": "2023-04-22",
    "end": "2023-04-23",
    "organization": "УРСТ",
    "foreign": false,
    "organizator": "Олександр та Катерина Мулляр",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 21,
    "title": "Відкритий чемпіонат міста Києва",
    "rating": true,
    "town": "Київ",
    "start": "2023-04-29",
    "end": "2023-04-30",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Ігор Соронович та Оксана Бойко",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 22,
    "title": "Зірки Олімпу",
    "rating": false,
    "town": "Київ",
    "start": "2023-05-06",
    "end": "2023-05-06",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "УАВТ",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 23,
    "title": "Dance Star Festival",
    "rating": false,
    "town": "Київ",
    "start": "2023-05-14",
    "end": "2023-05-14",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Сергій Тюткало",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 24,
    "title": "Кубок Тренера",
    "rating": true,
    "town": "Київ",
    "start": "2023-05-20",
    "end": "2023-05-21",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Олексій Грабовський та Марина Андрусенко",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 25,
    "title": "Spring Fantasy",
    "rating": false,
    "town": "Чернігів",
    "start": "2023-05-28",
    "end": "2023-05-28",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Алла Гордієнко",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 26,
    "title": "Cherkassy Summer",
    "rating": false,
    "town": "Черкаси",
    "start": "2023-06-03",
    "end": "2023-06-03",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Леонід Майстер",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 27,
    "title": "Каштани Києва",
    "rating": false,
    "town": "Київ",
    "start": "2023-06-03",
    "end": "2023-06-03",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Ігор Соронович та Оксана Бойко",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 28,
    "title": "Крок до зірок",
    "rating": false,
    "town": "Рівне",
    "start": "2023-06-03",
    "end": "2023-06-03",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Віталія Алєксєєва",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 29,
    "title": "Перша столиця",
    "rating": false,
    "town": "Харків",
    "start": "2023-06-04",
    "end": "2023-06-04",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Володимир Караченцев",
    "status": "Відкриті міські класифікаційні",
    "spartak": true,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 30,
    "title": "Black See Open Cup",
    "rating": true,
    "town": "Одеса",
    "start": "2023-06-17",
    "end": "2023-06-18",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Євген Герасименко",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 31,
    "title": "Inspiration Cup",
    "rating": true,
    "town": "Київ",
    "start": "2023-09-30",
    "end": "2023-09-30",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Андрій Євтєєв та Олександр Берьозін",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": true,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 32,
    "title": "Black See Ball",
    "rating": false,
    "town": "Одеса",
    "start": "2023-10-07",
    "end": "2023-10-07",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Євген Герасименко",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 33,
    "title": "Black See Ball",
    "rating": false,
    "town": "Київ",
    "start": "2023-10-07",
    "end": "2023-10-07",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Ярослав Скоренко та Сергій Тюткало",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 34,
    "title": "Золоті кроки Києва",
    "rating": false,
    "town": "Київ",
    "start": "2023-10-14",
    "end": "2023-10-14",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Анна Владикіна",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 35,
    "title": "Зірки України",
    "rating": false,
    "town": "Житомир",
    "start": "2023-10-15",
    "end": "2023-10-15",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Демʼян Кулик",
    "status": "Відкриті міські класифікаційні",
    "spartak": true,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 36,
    "title": "Star Dance Festival",
    "rating": true,
    "town": "Київ",
    "start": "2023-10-21",
    "end": "2023-10-21",
    "organization": "ВРСТ, УРСТ",
    "foreign": false,
    "organizator": "Віталій Руденко та Ірина Левіт",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 37,
    "title": "Cherkasy Open",
    "rating": false,
    "town": "Черкаси",
    "start": "2023-10-28",
    "end": "2023-10-28",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Леонід Майстер",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 38,
    "title": "Kyiv Grand Cup",
    "rating": false,
    "town": "Київ",
    "start": "2023-11-04",
    "end": "2023-11-04",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Юрій та Яна Васютяк",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 39,
    "title": "Осіння Феєрія",
    "rating": false,
    "town": "Тернопіль",
    "start": "2023-11-11",
    "end": "2023-11-11",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Ігор та Ольга Полигач",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 40,
    "title": "Star Up Dance",
    "rating": false,
    "town": "Чернігів",
    "start": "2023-11-12",
    "end": "2023-11-12",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Алла Савчук",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 41,
    "title": "Renaissance Cup",
    "rating": true,
    "town": "Дніпро",
    "start": "2023-11-18",
    "end": "2023-11-19",
    "organization": "ВРСТ, УРСТ",
    "foreign": false,
    "organizator": "Ольга Мальована та Кирило Мальований",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 42,
    "title": "Dance Sport Life",
    "rating": false,
    "town": "Київ",
    "start": "2023-11-18",
    "end": "2023-11-18",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Володимир Мачулка та Дмитро Белуха",
    "status": "Відкриті міські класифікаційні",
    "spartak": true,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 43,
    "title": "Відкритий чемпіонат міста Києва",
    "rating": true,
    "town": "Київ",
    "start": "2023-11-25",
    "end": "2023-11-26",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Ігор Соронович та Оксана Бойко",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 44,
    "title": "Золота осінь",
    "rating": false,
    "town": "Івано-Франківськ",
    "start": "2023-11-26",
    "end": "2023-11-26",
    "organization": "СГОСТУ",
    "foreign": false,
    "organizator": "Віталій Савчук",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 45,
    "title": "Luchesk Open Dance",
    "rating": false,
    "town": "Луцьк",
    "start": "2023-12-02",
    "end": "2023-12-02",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Сергій Застровськ ий",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 46,
    "title": "Київська Русь",
    "rating": false,
    "town": "Київ",
    "start": "2023-12-09",
    "end": "2023-12-09",
    "organization": "ВРСТ",
    "foreign": false,
    "organizator": "Олексій та Тетяна Балла",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 47,
    "title": "Різдвʼяний Бал",
    "rating": true,
    "town": "Рівне",
    "start": "2023-12-16",
    "end": "2023-12-17",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Роман Гриценюк",
    "status": "Відкриті всеукраїнські рейтингові",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  },
  {
    "id": 48,
    "title": "Christmas Cup",
    "rating": false,
    "town": "Київ",
    "start": "2023-12-23",
    "end": "2023-12-23",
    "organization": "УАВТ",
    "foreign": false,
    "organizator": "Леонід Майстер",
    "status": "Відкриті міські класифікаційні",
    "spartak": null,
    "about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, minus eum, officia esse deserunt error excepturi fugit dolores quidem aliquam iure. Placeat nam velit at magnam, atque ipsa quod doloremque architecto aut id ab adipisci, rerum odit nobis labore, culpa fuga dicta autem. Dignissimos, voluptate esse tempore architecto aliquid dolorum praesentium eveniet accusamus ad similique odit atque maxime porro hic iste dolores. Facilis eligendi labore dolores cumque dolor quidem perspiciatis aperiam corrupti, veritatis voluptate rerum modi repellat saepe commodi ex error obcaecati necessitatibus earum dignissimos, id, quasi eveniet quod? Dolores nisi ipsam doloribus distinctio velit dolorem nam maxime est deserunt."
  }
]`;

export const newsObj = `[
  {
    "id": 1,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 2,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 3,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 4,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 5,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  }  ,
  {
    "id": 6,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 7,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 8,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 9,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  }, 
  {
    "id": 10,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 11,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 12,
    "date": "0000-00-00",
    "title": "Новина",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  }
]`;

export const announcementsObj = `[
  {
    "id": 1,
    "date": "0000-00-00",
    "title": "Анонс",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 2,
    "date": "0000-00-00",
    "title": "Анонс",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  },
  {
    "id": 3,
    "date": "0000-00-00",
    "title": "Анонс",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae culpa, recusandae excepturi."
  }  
]`;

export const dancersData = `[
  {
    "id": 1,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 2,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 3,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 4,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 5,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 6,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 7,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 8,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 9,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 10,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 11,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  },
  {
    "id": 12,
    "name": "Іван",
    "surname": "Іванов",
    "thirdname": "Іванович",
    "birthday": "2003-05-12",
    "class": "C",
    "club": "Diamant-Elite",
    "organization": "СГОСТУ"
  }
]`;
